### ISSUE TITLE
Додати шаблон корзини

### ISSUE THREAD

**Issue by Duvie-Gazda** [UzhKeksy-2-0/Flower-Shop#1]
Додати шаблон корзини. Перелік товарів треба просто розмітку нічого туди не закидаючи туди ніяку інформацію
* Має бути
  * перелік товарів - просто розмітка (виділити місце на це)
  *  `total price` - ціна всіх товарів
  * кнопка перейти на оформлення замовлення

**Comment by Duvie-Gazda** [comment]
complete

**Comment by XBaTuT** [comment]
Ready.
