### ISSUE TITLE
Додати шаблон сторінки товару

### ISSUE THREAD

**Issue by Duvie-Gazda** [UzhKeksy-2-0/Flower-Shop#2]
Додати шаблон сторінки товару. допоміжні фотографії можуть бути будь-де приклад не вказує як має бути він вказує що так може бути. Відгуки відгуків не треба туда нічого писати просто виділити місце для них. Порядок не обов'язковий
* Має бути
  * категорія товару
  * назва товару 
  * ціна товару
  * вибрати кількість товару (від кількості вибраних товарів збільшується ціна)
  * головна фотографія товару
  * другі фотографії (допоміжні)
  * короткий опис 
  * повний опис 
  * зірочки оцінювання 
  * кнопка додати до кошика (яка надсилає дані :  кількість товару та id товару)
  * розмітка для переліку відгуків
  * розмітка для додавання відгуку
[Приклад](https://prnt.sc/vunigo)

**Comment by XBaTuT** [comment]
Ready

**Comment by XBaTuT** [comment]
Ready.
