### ISSUE TITLE
Додати шаблон сторінки 404 

### ISSUE THREAD

**Issue by Duvie-Gazda** [UzhKeksy-2-0/Flower-Shop#20]
Додати шаблон сторінки 404 
Має бути:
  * текст `404 . Вибачте але ця сторінка не є доступна` або щось у цому стилі
  * кнопка для переходу на головну сторінку (поки просто кнопка з текстом `Головна` або `Додому`)

**Comment by Duvie-Gazda** [comment]
в інеті дуже багато прикладів якщо хочеш вибери який тобі більше подобається. Просто я не знаю який кращий

**Comment by XBaTuT** [comment]
Ready.
