### ISSUE TITLE
Додати шаблон Про нас

### ISSUE THREAD

**Issue by Duvie-Gazda** [UzhKeksy-2-0/Flower-Shop#37]
Додати шаблон сторіни про нас. Просто статичний текст на англ мові. Можна із картинками (якісь люди...)
![image](https://user-images.githubusercontent.com/59282220/101294244-cded7e00-381e-11eb-8908-4bff696cdd39.png)
# Приклад 2
![image](https://www.slidegeeks.com/pics/dgm/l/a/About_Us_Ppt_PowerPoint_Presentation_Infographic_Template_Layout_Slide_1-.jpg)
# Приклад 3

![image](https://user-images.githubusercontent.com/59282220/101294332-47856c00-381f-11eb-979a-8138cfecc5dd.png)

**Comment by XBaTuT** [comment]
Ready.
