### ISSUE TITLE
Додати шаблон Контакти

### ISSUE THREAD

**Issue by Duvie-Gazda** [UzhKeksy-2-0/Flower-Shop#38]
Додати шаблон конткактної інформації (просто наша адресса, номер телефону,  карта...). Із цого переліку не обов'язково всі пункти, або иожна додати свої, але щоб вони були прості і не потребували нічого серйозного (типу напішіть нам буде для нас трохи вжкувато зробити). Просто статичний текст
# Приклад 1
![image](https://user-images.githubusercontent.com/59282220/101294482-3426d080-3820-11eb-85db-02bf55c46b6e.png)
# Приклад 2
![image](https://user-images.githubusercontent.com/59282220/101294501-5882ad00-3820-11eb-9012-c89aaaa00d5f.png)
# Приклад 3
![image](https://user-images.githubusercontent.com/59282220/101294515-66d0c900-3820-11eb-8e81-4d6419bbf2f9.png)

**Comment by XBaTuT** [comment]
Ready.
