### ISSUE TITLE
Додати шаблон домашньої сторінки

### ISSUE THREAD

**Issue by Duvie-Gazda** [UzhKeksy-2-0/Flower-Shop#5]
Додти домашню сторінку, у якій має бути:
   1. Перелік категорій (тільки розмітка, не треба тут додавати туди даі просто виділити місце для переліку категорій)
   2. Перелік товарів (тільки розмітка, не треба тут додавати туди даі просто виділити місце для переліку категорій)

**Comment by Duvie-Gazda** [comment]
[Приклад](https://prnt.sc/vuivhw) (не обов'язково точно таку розмітку)

**Comment by XBaTuT** [comment]
Ready.
