### ISSUE TITLE
Додати шаблон сторінки вхід

### ISSUE THREAD

**Issue by Duvie-Gazda** [UzhKeksy-2-0/Flower-Shop#6]
Додати шаблон для входу юзерів
* Має бути 
  * Лого сайту (поки люба фотографія)
  * Введення логіну
  * Введення пароля
  * Кнопка вхід
  * Перенаправлення на реєстрацію (просто текст із посиланням)
[Приклад](https://prntscr.com/vumztx)
`запам'ятати мене` - не потрібно

**Comment by XBaTuT** [comment]
Ready.
