### ISSUE TITLE
Додати шаблон реєстрації

### ISSUE THREAD

**Issue by Duvie-Gazda** [UzhKeksy-2-0/Flower-Shop#7]
Додати шаблон html реєстрація клієнта
 * Має бути 
  * логін
  * пароль
  * підтвердити пароль
  * email - не обовязкове поле на формі (його не обов'язково вводити але воно має бути на формі)
  * phone
  * adress - не обовязкове поле на формі (його не обов'язково вводити але воно має бути на формі)

**Comment by XBaTuT** [comment]
Ready.

**Comment by XBaTuT** [comment]
Totally ready.
